### ISSUE TITLE
IndexOutOfBounds

### ISSUE THREAD

**Issue by Towsty** [Elecs-Mods/ElecCore#10]
We get this crash almost every time the server restarts. To fix it I seem to have to remove/rename the elec332 folder in the world folder.

Crash Report:
http://pastebin.com/kaQ6v2aW

Server Log: (crash lines around 44748)
https://drive.google.com/open?id=0B4UhGIFXzCO6Y2JFRS1vT1dqeXc

**Comment by spannerman79** [comment]
Having the exact same issue.

ElecCore-1.7.10-1.4.176.jar
Forge 1614

[crash-2016-01-30_03.08.34-server.txt](https://github.com/Elecs-Mods/ElecCore/files/110044/crash-2016-01-30_03.08.34-server.txt)

Only way to fix it is to do what @Towsty has stated, `rm -rf elec332/`

**Comment by ghost** [comment]
Also the same issue:

ElecCore-1.7.10-1.4.174.jar
KCauldron 1.7.10-1492.152

Crash Report: http://pastebin.com/XDWXgtC7

Renaming the file generated a new one and things were able to load then. (No crashing)

**Comment by BBoldt** [comment]
https://gist.github.com/b294569f06b1478aca90

:cry:

**Comment by Elec332** [comment]
@BBoldt You issue is different, and was introduced in one of the latest releases.
To make the file loading easier (and hopefully more reliable), I had to rewrite parts of it.
This unfortunately means that it will crash upon loading an old world. This can be fixed by removing the elec332/ folder in the world. The issue above has been fixed already.
